# Generated by Django 4.2 on 2024-11-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='books/')),
                ('book_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
